function  run_cat_rtp_daily()
% CREATE_CAT_RTP_DAILY 
%
% read in a directory of rtp files (most likely constituting a day
% of data) and concatenate them into a single output rtp
% file. Calls cat_rtp_dir() which does the bulk of the actual
% concatenation. This routine drives input/output selection and
% does the final rtpwrite

addpath('~/git/rtp_prod2/util');  % rtpread,rtpwrite,cat_rtp_dir

% 
cris_daily_file_list = '~/cris-days-to-process';

% grab the slurm array index for this process
slurmindex = str2num(getenv('SLURM_ARRAY_TASK_ID'));

% for each slurm array index, process 30 days from the to-process
% list (because each day takes less time to process than it takes
% to load matlab so, it is inefficient to to do each day as a
% separate array)
chunk = 30;
for i = 1:chunk
    dayindex = (slurmindex*chunk) + i;
    fprintf(1, '>>> chunk %d    dayindex %d\n', i, dayindex);
    
    % File ~/cris-files-process.txt is a list of filepaths to the input
    % files or this processing. For the initial runs, this was
    % generated by a call to 'ls' while sitting in the directory
    % /asl/data/cris/ccast/sdr60_hr/2015: 
    %    ls -d1 $PWD/{048,049,050}/*.mat >> ~/cris-files-process.txt
    %
    % cris-files-process.txt, then, contains lines like:
    %    /asl/data/cris/ccast/sdr60_hr/2015/048/SDR_d20150217_t1126169.mat
    [status, indir] = system(sprintf('sed -n "%dp" %s | tr -d "\n"', ...
                                     dayindex, cris_daily_file_list));
    if strcmp(indir, '')
        break;
    end

    % generate output file name and path (presently to be
    % /asl/data/rtp_cris_ccast_lores/clear_daily/<year>/rtp_d<date>_clear.rtp)
    C = strsplit(indir, '/');
    sYear = C{6};
    outpath = fullfile('/asl/data/rtp_cris_ccast_lores/clear_daily', ...
                       sYear);

    % read in filenames in indir to build output filename
    mfiles = dir([indir '/rtp_*.rtp']);
    [path, name, ext] = fileparts(mfiles(1).name);
    C = strsplit(name, '_');
    outfile = fullfile(outpath, [C{1} '_' C{2} '_clear.rtp']);

    % concatenate rtp files in indir
    [h,ha,p,pa] = cat_rtp_dir(indir);

    % write out concatenated rtp file
    try
        rtpwrite(outfile, h,ha,p,pa);
    catch
        fprintf(2, '>>> rtpwrite failure in chunk %d for %s\n', i, indir);
    end
    
end  % ends loop over chunk
%% ****end function run_cat_rtp_daily****