function run_climcaps_rtp(cfg)

% granule names look like
% SNDR.SNPP.CRIS.20160120T2312.m06.g233.L1B_NSR.std.v01_00_00.W.160311164050.nc
%
% and source from
% /home/strow/Work/Cris/Nasa/L1b/beta3

% grab the slurm array index for this process
slurmindex = str2num(getenv('SLURM_ARRAY_TASK_ID'));

% offset slurmindex to bypass MaxArraySize boundary
%slurmindex = slurmindex + 19999

chunk = cfg.chunk;
for i = 1:chunk
dayindex = (slurmindex*chunk) + i;
fprintf(1, '>>> chunk %d  dayindex %d\n', 1, dayindex);

% File ~/cris-files-process.txt is a list of filepaths to the input
% files or this processing. For the initial runs, this was
% generated by a call to 'ls' while sitting in the directory
% /asl/data/cris/ccast/sdr60_hr/2015: 
%    ls -d1 $PWD/{048,049,050}/*.mat >> ~/cris-files-process.txt
%
% cris-files-process.txt, then, contains lines like:
%    /asl/data/cris/ccast/sdr60_hr/2015/048/SDR_d20150217_t1126169.mat
[status, infilepath] = system(sprintf('sed -n "%dp" %s | tr -d "\n"', ...
                                  dayindex, cfg.file_list));

if strcmp(infilepath, '')
    return;
end
    % process netcdf file to rtp
    [h,ha,p,pa] = create_rtp_climcaps(fnCrisInput,cfg);

% build output file path and name
C = strsplit(files(1).name, '.');
% SNDR.SNPP.CRIS.20170903T1142.m06.g118.L1B.std.v02_05.G.180615223853.nc
D = extractBetween(C{4},1,8);
sName = ['SNDR.SNPP.CRIMSS_' D{1} '_random.rtp'];

C = strsplit(infilepath, '/');
outfilepath = fullfile(cfg.outputdir, 'random', C{end-1}, C{end});
if exist(outfilepath) == 0
    mkdir(outfilepath);
end
fnOutFile = fullfile(outfilepath, sName);
fprintf(1, '>> Writing output rtp to: %s\n', fnOutFile)
rtpwrite(fnOutFile, head, hattr, prof, pattr);

end % end loop over chunk
fprintf(1, '> Done\n');
